Readme
SemenSofronov/tour-addon pull request #1
Opened 2018-09-04 07:05 UTC by SemenSofronov

2018-09-04 07:33 UTC, glebfox requested changes

2018-09-04 07:33 UTC, glebfox commented on README.md
> +Этот аддон предоставляет возможность создавать навигационные туры для экранов в приложениях
Непонятно, что такое "навигационные туры". Поищи грамотное название на русском и/или в скобках добавь грамотное название на английском, все равно потом переводить.

2018-09-04 07:33 UTC, glebfox commented on README.md
> + - [Vaadin Addon for creating Product Tours](https://github.com/Juchar/product-tour)
У тебя нет зависимостей, мы же зашейдили Ваадин аддон у нас.

2018-09-04 07:33 UTC, glebfox commented on README.md
> +- Tour
Добавь описание классов: что, зачем, почему

2018-09-04 07:33 UTC, glebfox commented on README.md
> +com.haulmont.addon.tour:tour-global:0.1-SNAPSHOT
1.0.0 же версия будет

2018-09-04 07:33 UTC, glebfox commented on README.md
> +Для создания тура необходим компонент, реализующий интерфейс Tour. С помощью метода `addStep` к туру можно привязать
> ... необходим компонент, реализующий интерфейс ...
Ты фрустрируешь читателя. Просто перечисли классы реализующие твои интерфейсы после этого абзаца.

2018-09-04 07:33 UTC, glebfox commented on README.md
> +Также создать тур можно при помощи `TourParser` из json вызовом метода `parseTour`, который на вход принимает json,
> из json
Это убери, а то у тебя масло масляное получается

2018-09-04 07:42 UTC, glebfox requested changes

2018-09-04 07:42 UTC, glebfox commented on README.md
> +Для создания кнопки добавьте следующий блок к `buttonsPanel` в product-browse.xml:
не блок, а компонент

2018-09-04 07:42 UTC, glebfox commented on README.md
> +При инициализации страницы `ProductBrowse` мы будем парсить тур из json файла.
Напиши, где файл лежит, чтобы читателям не пришлось по коду разбирать

2018-09-04 07:42 UTC, glebfox commented on README.md
> +productBrowseTour.json:
Опиши JSON файл подробнее. Почему у тебя массив объектов, кто из них кто и т.д.

2018-09-04 07:42 UTC, glebfox commented on README.md
> +    TourParser tourParser = AppBeans.get(TourParser.class);
Заинжекть

2018-09-04 07:42 UTC, glebfox commented on README.md
> +    String file = resources.getResourceAsString("com/company/touraddondemo/web/product/productBrowseTour.json");
Строка слишком длинная и приходится скролить код

2018-09-04 07:42 UTC, glebfox commented on README.md
> +Для `ProductEdit` будем парсить тур из json таким же образом, только укажем путь к файлу productEditTour.json.
Ты уже показал подход с json, покажи как программно сделать то же самое

2018-09-04 07:42 UTC, glebfox commented on README.md
> +Для отображения локализованных сообщений необходимо добавить их в messages.properties:
оберни messages.properties в косые одинарные кавычки ``

2018-09-04 07:42 UTC, glebfox commented on README.md
> +tour.createButtonText = <p>This is a <b>create button</b>.</p> <p>Press the button to open an editor screen to \
Этот файл какое то мясо. Везде, где начинается тег абзаца, переноси строки.

2018-09-04 07:42 UTC, glebfox commented on README.md
> +Next, we need to create a theme extension in Project Properties.
Зачем? Расскажи читателям для чего это надо.

2018-09-04 07:42 UTC, glebfox commented on README.md
> +![](screenshots/4-run-application-product-browse.png "View of the ProductBrowse screen in the running app")
У тебя на скринах диалог запуска тура находится в нижнем правом углу, хотя по факту по центру экрана. Сделай норм скрины, чтобы позиционирование было так как оно есть в работающем приложении.

2018-09-04 07:44 UTC, SemenSofronov commented on README.md
> +![](screenshots/4-run-application-product-browse.png "View of the ProductBrowse screen in the running app")
Я подумал, что получатся слишком большие скрины

2018-09-06 08:51 UTC, glebfox requested changes

2018-09-06 08:51 UTC, glebfox commented on README.md
> +Если мы сейчас запустим приложение, то увидим, что наши новые компоненты отображаются некорректно. Классы, необходимые
Не надо писать, что будет ошибка или что то будет работать некоректно. Просто напиши зачем надо создать расширение темы.

2018-09-06 08:51 UTC, glebfox commented on README.md
>  ![](screenshots/3-theme-extention.png "Create extension theme")
У тебя там ниже скрины запущенного тура (не могу на них коменты туту сделать). Ты хоть что то можешь на них разобрать? у меян на экране замылиное нечто, с кучей пустого места.

2018-09-06 08:51 UTC, glebfox commented on README.md
> +Этот аддон содержит набор компонентов, позволяющих создавать product tour по пользовательским экранам.
Если в кратце, то я из этого описания нифига не понял

2018-09-06 11:10 UTC, glebfox requested changes

2018-09-06 11:10 UTC, glebfox commented on README.md
>  ![](screenshots/3-theme-extention.png "Create extension theme")
У тебя на скрине editentities слитно написано. Нужны скрины с шагом, указывающим на компонент. Хотя бы по одному для Браузера и Эдитора.

2018-09-06 12:19 UTC, glebfox requested changes

2018-09-06 12:19 UTC, glebfox commented on README.md
> +Так выглядит `ProductBrowse` screen с шагом, привязанным к компоненту:
А не логичнее будет показать сперва скрины для Браузера, а потом для Эдитора?

2018-09-06 12:26 UTC, glebfox approved these changes

2018-09-06 12:27 UTC, merged